apiVersion: ENC[AES256_GCM,data:D4o=,iv:FBYIh/ubr5Vvp993HKpQ1jyIu6BqQDaA9YcVDdluv50=,tag:cJTpiPkXqBwL4Qs2x5/h+g==,type:str]
kind: ENC[AES256_GCM,data:mLTpQcDV,iv:+nk3uceUX7FdsWLfEgCU8EYRxPE0sOgxfTN18MxC6ho=,tag:YEWzeqVmGX/luWIm2u+5UQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:di8z+XLJyJMaHyRadBcl3sudVm7oTQ==,iv:HK3Y1SpUO6CNX960REch/CQgu/QpvU4xYXdR50Sooss=,tag:h0V/OLe+lWFvVsTaJVRQfQ==,type:str]
    namespace: ENC[AES256_GCM,data:X7vJ79Wp,iv:PPUDpgRcmRvzcHN0FMVO7bSa4W5zsE7dpYKeUJGy/G4=,tag:NlAahUeKyH9Dyksk4U/lfQ==,type:str]
type: ENC[AES256_GCM,data:915CvEAY,iv:mHszfN+1nDwGOHKzU+SbT4rkKXEc5WVFMWaI1pk89r0=,tag:pKAZT2+Vud06FeWCLnhMLA==,type:str]
stringData:
    OPENAI_API_KEY: ENC[AES256_GCM,data:LPw5BXJL2fNR7K/XxnXoPQtzzlileo2pGt28HA==,iv:DPYPJUAEZSpZFz6aIufocFBJUFC1KilfM54+982GJQQ=,tag:CL4MyreHR0WyKxKCzSZ0Gg==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:QOX8ClXFC1YL1qXvUCD+rTBZGL/cu4FKqueylw==,iv:NlE+4Y7WRbc15lnuVWqFj7Ff94OOrQw3cBznjH03tPo=,tag:YeeyiCvQyG952jRBIWaIbw==,type:str]
sops:
    age:
        - recipient: age150mcr0vkltgr854rjnydst80r50rj5uc7tt24h0kaewru3r45vysyh7cns
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMNUI2UkRKZXNqWEpDaVhj
            YXlQZnNBS21CdmJsN0I0dVhWSnpUeWpEbWk0ClBIaWRjTnl0STQ4VFE2MmtXRWZI
            R0lTeEo2NHlmZ2hQZDZDU0VMVS93UTgKLS0tIGpvWW5vc3Nsa0hraE9EYzZYVTAx
            Q2ludDRjbThqRC93ZXArRm5GTlpreVEKHDkMG6qJtV60Xhbn7RdB+D2mUyQMNejf
            IYasqo4k90L38I4KNQ0oenMrr/+KnoNYW+Nk2KcNrzijoVtLSL2vTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-28T03:17:47Z"
    mac: ENC[AES256_GCM,data:TmRM6pI7XRriNe+Yt5CW9UVqXMh0w6oed7W8NX583k9K3YkLmwq+aMlj1kjKaaiibV/Ii+j7KHEvRCcwEx2XkyTOlql1HEC5JoY/n+EERrmr9RzT244nvdMhAtmsuaIiesJ3j1It9mBItXcG3sX+VUdHVo/0a4KlaLFq6K6OYNo=,iv:5ZqEY4+JFAbqdn7T6d2D0qH8Kn/n49gWpd+45uqrhds=,tag:E5dS1W++6XNi3AZkLXKxAg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
