apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: msp360-chatbot
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/sherrygill2012-web/mspbackups_chatbot.git
    targetRevision: HEAD
    path: k8s
    plugin:
      name: ksops-v1.0
  destination:
    server: https://kubernetes.default.svc
    namespace: msp360
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
