---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: msp360-chatbot-secrets
  namespace: msp360
spec:
  encryptedData:
    GEMINI_API_KEY: AgACwbzuf0e9mebT9QWKkW6ivHiVAb5WT8Y5FEZXA4YwGm0xc+vVQJfOJDEgjGnD8t+uD0EYiuk9jHJUzNy1yKzH5fX4N+ZCwgaGbn1qjEcyAu7/HIpGVUyzPwgi1oNQqomVt4MU0H3bJZAEP/TB2N2nuyGIuwaeU2mjohf843PPVXIJhT0EgGJ2MXxb+gWWMi2ZzA0cmflXRvQrpKflvRgCK0LefUkLhn4RDOnmTAzh2AwP3BivxFl1jz3fbKrqlf0NXih1yX+FV+Yk6eG8+KF2NzFm6gUfDleE+5f3KPWTtAxQjdvwpy+kW1fkCjFDJsednRDLFZEueSxw28cy69rs2BQSi+DaAeACF0AAoMFArIe+9KHLxS7CH4U5yQ3XdG75LtcHcLp67xLcH2Bziaexrv+6+WGQIl70JHZFcuJgmWK4RgqbyCTG+5Q+F9dLnRQ4hq9/draviyg3EsLw5r3K0tU0ijdsAx7jSt58oGJQoGvfgb2jgM+FO7kHXK9bdDXXmbKKCTXLnydes9nf5ipJNax7AZbw4U3wlddvoYfTmcCQ+93FPIoVarRtbYHaTn5pLhPXYmEALRuS3w2GcOOLLaQcohgzkg90eFy6SGkB8FgLi3qnC/Hx00C/TSVLAkPyW7iMngoBj4J8MowpRP+WvRNUsQaBft/RcKXJUaZ1s1GFzPxMVjHSLRhEe46MJ+388bX3IB/VpwAAbcpyOsXhlsZ1rMKTDTQHSRLK
    OPENAI_API_KEY: AgA0F6ayjv+LIU4W0TiLi0mWlsM+he0pzjFFAvDnSkxmDhXtmhazE0+TIloamGHpCbKM5VtKlV54Q0n3SJ0kGWB9P76OFzUCp5UzIIt1pV8TETupwaVKqgWFxkO41apwV2kUgtu2QSeuoQzfixDbU39xq1XhnA4zBaRQ0+98zY1brm5m//vs0ehSZ47qFV11CfCIdjjQ7z9ti+SWORlw5X0ZXcz5FABbBiV3i1lj84Vc1IAfjvaKmjZmODcPo+kyLeHhpKGbwxLsKa3ll0b2MTceYGjwE1/7MI4wstz1/xxKv5XwjG4J05IOgshW9wZVp4cffFgSUQKiR2zGVL52d6fhF5i5cWk13xYmpsgoiPzvzekXuvemAtfz7hbUutfBILH+df9QRoNzm+JfJAPokFwpWNVXOnefBw3a46HTzEBy0NvaH1cA4Q0F+ZyyF7BaQNixj5Q54TRp7Btk+VK/h3zaVzWUOWovpNf1XnaTLnyznEddkjyzCISbJNSxJ9JmOEMb6p4QtXXvCNZIRaKV6pBiFWp2NBrwTtfZInaOPa9QE1RWJsjaJ1vPxWhjkLk3c5fit1hvDE1HRyceAznUksgpikAFP1380w+WS54LjHyoPMw121lcKuJ2NIrBGE+9ELj/D4uTKFi9KEYtGkBSJFQrye7kt1q0LQYcyJ8bXkhkn9tnoyhOLJ2x6ZE9vcQRa7aaQ405hf2Rv+s7OHPULERMwnuAVfUbIuouKAl5
  template:
    metadata:
      name: msp360-chatbot-secrets
      namespace: msp360
    type: Opaque
