---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: msp360-chatbot-secrets
  namespace: msp360
spec:
  encryptedData:
    GOOGLE_API_KEY: AgBd0xJ1sxr/XnGch3j0FEIkJNpOW7ySgoJGZwn4y1eWxVomxT0/C+Z+2CDu2iwdho5XuRz1FKsGmMWTyzOXVS2tucGX8aZWh5tOgEVBCHNSXj6XfXDk5peW1cxPev53+/QSlMsr0KSP3AkzSAwrzo8ALToqbc+xPHcd06fEGSWXYXrXVngHP1pntqDJVY7NyRLY+7P2I7LTQ6s38MP2o5EbA9dfvQrTofM+SbKYc4hg1mreF2ROz1ZARLVpTjn0h47cz6/NcDXwMeyKWvJir/U1Ig/m34CoobsE6g1L2XmOSOTmnAk5J6Bdc2klnJLjkmuz+P2YkeDViU4S9LuJv9mopiQ4pZglQcozPqK62P3Z833bICjS5i9F/u8u6EeHYOfe02KSvBGLG6FyghObnonsdUQShegv9Hw1hXvF1LJ5SAHZ+l4b1iC2BA2M0WVBFGpHTSkpdlLW3Wdx/gQOAiiPSS+0YDycNtrfxPCWvO0xSNbZB2OQ0p1x6hheR19Mh1xmZsoyWXwi5Zf9+hL65thoS7pGWCFTPuhhjWPzu2lrLLphDVKtC1bUb3LtZy5eH4kQV0WmTezbDxmr2eA4e+pooGaWH7GBgEIEwxwzF3sm5d049YIP+D/QlwsyQUFvz1FCMuIZAdYPT344vKClPURO2mBhD0otzF/Hs9YBSLxfOHOyEpZpi4FmB+p8H6rxDOw3p9tgZ2sqjYW9KFbLmMyC7JC72i9WqkTZ2JF4caYMz24JJeCKu24=
  template:
    metadata:
      creationTimestamp: null
      name: msp360-chatbot-secrets
      namespace: msp360
