apiVersion: v1
kind: Service
metadata:
  name: msp360-chatbot
  namespace: msp360
spec:
  type: NodePort
  selector:
    app: msp360-chatbot
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30850  # Access via http://<node-ip>:30850


